### ISSUE TITLE
It worked after install but...

### ISSUE THREAD

**Issue by carine-lawson** [Vertagon-Softworks/Chromo#3]
Now its not... 5 min later. No colors are showing and ctrl-alt-o doesn't do anything and clicking in packages menu and chromo there...toggling, doesnt' do anything either

**Comment by carine-lawson** [comment]
<img width="418" alt="Screen Shot 2019-10-04 at 2 04 51 PM" src="https://user-images.githubusercontent.com/52208854/66229522-00966680-e6b0-11e9-92c9-602021bb007c.png">

**Comment by carine-lawson** [comment]
restarted atom a few times.. it finally came back.

**Comment by carine-lawson** [comment]
Nevermind. I want to reopen. it keeps happening and I haven't figured out the trigger but one minute its there and the next its not... i have to restart atom to get it to appear again.

**Comment by Vertagon-Softworks** [comment]
Hey carine-lawson,

I'll take a look at this when I get a chance. I suspect there is an exception that isn't being caught, so I'll update here and push and update when I figure something out.

**Comment by Vertagon-Softworks** [comment]
I just pushed some stability fixes to the newest version (1.7). Give it a try and let me know if the issues still persist.

Thanks!
