### ISSUE TITLE
wrong color-preview if CSS-variables are named by colors

### ISSUE THREAD

**Issue by webgestalter** [Vertagon-Softworks/Chromo#4]
Hey, i found a issue:

if i name my CSS variables for colors by colors

![chromo 1 1](https://user-images.githubusercontent.com/56323040/66702052-8a26e380-ed03-11e9-9fa9-ce0d9e1d7d6a.png)

it won't get the color codes i set for but detects it by name of the standard ones i guess

![chromo 1 2](https://user-images.githubusercontent.com/56323040/66702083-dffb8b80-ed03-11e9-831b-49c3689fd5f4.png)

cheers!

**Comment by Vertagon-Softworks** [comment]
Hey @webgestalter I'll get to fixing this in the next update. Sorry for the issues on this, and thanks for your feedback!

**Comment by Vertagon-Softworks** [comment]
I just pushed an update (1.7) that fixes some issues related to this. Try it out and let me know if the issues still persists.

Thanks!
